### ISSUE TITLE
Investigate suspend / resume

### ISSUE THREAD

**Issue by mstauff** [mstauff/cwf-android#2]
We need to understand how we save state and any data (ward list, calling data, etc) during a suspend, and how to restore on a resume.

**Comment by admshepherd** [comment]
![activity_lifecycle](https://cloud.githubusercontent.com/assets/2212572/20984641/6422507e-bc7e-11e6-8a92-5f28fca4d277.png)
Here is the basic life cycle map for an android activity. These functions are automatically called by the system based on user actions and system resources. The states which an activity will remain in are: 

Running - Activity has current focus on the device
Paused - Activity has lost focus but is still partially visible on the screen
Stopped - Activity is no longer visible to the user
Destroyed/killed w/ Saved State - Activity is removed to reclaim needed resources
Destroyed - Activity ended through finish() call, back button, or saved state info discarded

The methods in the map are executed in quick succession until the appropriate state has been reached. There are more event methods than this. One important one is onSaveInstanceState(Bundle) which runs sometime before onStop() if the Activity will be entering a killable state. State information is saved as key/value pairs in the bundle and which is then passed to onCreate(Bundle) and onRestoreInstanceState(Bundle) when recreating the Activity. We can override these methods in our activities to preform proper startup and shutdown tasks for the given screen. When overriding these methods we must call their super methods to preserve their default functionality. In the case of onSaveInstanceState(Bundle), the super method removes current values from the bundle so it should be called before saving anything to the bundle.

It's important to note that onDestroy() doesn't always run and shouldn't be used for preserving data. Rather it's for releasing resources such as those that may be kept alive by the application when they were only needed by the Activity.

Any configuration change such as language or orientation will cause the activity, not the application, to be destroyed and recreated.

The application follows similar rules of when it may be killed, but it doesn't have any event methods for saving state. Any application level info that hasn't been cached to disk storage is lost when the process is ended.
