### ISSUE TITLE
Calling Detail - Top right options

### ISSUE THREAD

**Issue by mstauff** [mstauff/cwf-android#38]
should provide an action popup with options to delete & release. Clicking either gives a confirmation dialog. We don't need the actual functionality yet, that's still TBD

**Comment by mstauff** [comment]
![screen shot 2017-04-12 at 2 35 55 pm](https://cloud.githubusercontent.com/assets/2190700/24978351/94c2705c-1f8d-11e7-988c-b073cca9cd0e.png)

**Comment by blanchardb** [comment]
Stubbed in the menu onclick items.  We still need to hook into LCR for the Relase of current member and Delete of current calling in LCR.
